In [1]:
import numpy as np

class HopfieldNetwork:
    def __init__(self, num_neurons):
        self.num_neurons = num_neurons
        self.weights = np.zeros((num_neurons, num_neurons))

    def train(self, patterns):
        for p in patterns:
            self.weights += np.outer(p, p)  # Use np.outer for Hebbian learning
        np.fill_diagonal(self.weights, 0)  # No self-connections

    def recall(self, input_pattern, steps=5):
        pattern = input_pattern.copy()
        print(f"\nRecalling pattern: {pattern}")
        for _ in range(steps):
            for i in range(self.num_neurons):
                raw_input = np.dot(self.weights[i], pattern)
                pattern[i] = 1 if raw_input >= 0 else -1
            energy = self.energy(pattern)
            print(f"Pattern: {pattern}, Energy: {energy}")
        print(f"Final recalled pattern: {pattern}")
        return pattern

    def energy(self, pattern):
        return -0.5 * np.dot(pattern.T, np.dot(self.weights, pattern))


# Define 4 binary patterns (bipolar values: 1 and -1)
patterns = np.array([
    [1, -1, 1, -1],
    [-1, 1, -1, 1],
    [1, 1, -1, -1],
    [-1, -1, 1, 1]
])

# Create Hopfield network
hopfield_net = HopfieldNetwork(num_neurons=4)

# Train the network using np.outer
hopfield_net.train(patterns)
print("Weight matrix after training:")
print(hopfield_net.weights)

# Test with known and noisy patterns
test_patterns = [
    [1, -1, 1, -1],
    [1, 1, 1, -1],
    [-1, 1, 1, 1]
]

for test in test_patterns:
    hopfield_net.recall(np.array(test))


Weight matrix after training:
[[ 0.  0.  0. -4.]
 [ 0.  0. -4.  0.]
 [ 0. -4.  0.  0.]
 [-4.  0.  0.  0.]]

Recalling pattern: [ 1 -1  1 -1]
Pattern: [ 1 -1  1 -1], Energy: -8.0
Pattern: [ 1 -1  1 -1], Energy: -8.0
Pattern: [ 1 -1  1 -1], Energy: -8.0
Pattern: [ 1 -1  1 -1], Energy: -8.0
Pattern: [ 1 -1  1 -1], Energy: -8.0
Final recalled pattern: [ 1 -1  1 -1]

Recalling pattern: [ 1  1  1 -1]
Pattern: [ 1 -1  1 -1], Energy: -8.0
Pattern: [ 1 -1  1 -1], Energy: -8.0
Pattern: [ 1 -1  1 -1], Energy: -8.0
Pattern: [ 1 -1  1 -1], Energy: -8.0
Pattern: [ 1 -1  1 -1], Energy: -8.0
Final recalled pattern: [ 1 -1  1 -1]

Recalling pattern: [-1  1  1  1]
Pattern: [-1 -1  1  1], Energy: -8.0
Pattern: [-1 -1  1  1], Energy: -8.0
Pattern: [-1 -1  1  1], Energy: -8.0
Pattern: [-1 -1  1  1], Energy: -8.0
Pattern: [-1 -1  1  1], Energy: -8.0
Final recalled pattern: [-1 -1  1  1]


In [2]:
import numpy as np

class HopfieldNetwork:
    def __init__(self, size):
        self.size = size
        self.weights = np.zeros((size, size))

    def train(self, patterns):
        """Train the network using Hebbian learning."""
        for p in patterns:
            p = np.reshape(p, (self.size, 1))
            self.weights += np.dot(p, p.T)
        np.fill_diagonal(self.weights, 0)  # No self-connections

    def activate(self, x):
        """Activation function: Sign function."""
        return np.where(x >= 0, 1, -1)

    def recall(self, pattern, steps=10):
        """Recall a stored pattern asynchronously."""
        pattern = np.array(pattern)
        for _ in range(steps):  # Iterate to reach a stable state
            for i in range(self.size):
                net_input = np.dot(self.weights[i], pattern)
                pattern[i] = self.activate(net_input)
        return pattern

# Define stored patterns (4 vectors)
patterns = np.array([
    [1, -1, 1, -1, 1, -1],
    [-1, 1, -1, 1, -1, 1],
    [1, 1, -1, -1, 1, 1],
    [-1, -1, 1, 1, -1, -1]
])

# Create and train the Hopfield Network
hopfield_net = HopfieldNetwork(size=6)
hopfield_net.train(patterns)

# Test with input patterns (can be noisy)
test_patterns = np.array([
    [1, -1, 1, -1, 1, -1],   # Exact match
    [-1, 1, -1, 1, -1, 1],   # Exact match
    [1, 1, -1, -1, 1, -1],   # Slightly noisy
    [-1, -1, 1, 1, -1, 1]    # Slightly noisy
])

# Recall stored patterns
print("Recalled Patterns:")
for test in test_patterns:
    output = hopfield_net.recall(test)
    print(output)


Recalled Patterns:
[ 1 -1  1 -1  1 -1]
[-1  1 -1  1 -1  1]
[ 1  1 -1 -1  1  1]
[-1  1 -1  1 -1  1]
