In [2]:
import numpy as np

class HopfieldNetwork:
    def __init__(self, num_neurons):
        self.num_neurons = num_neurons
        self.weights = np.zeros((num_neurons, num_neurons))

    def train(self, patterns):
        for p in patterns:
            p = np.reshape(p, (self.num_neurons, 1))
            self.weights += np.dot(p, p.T)
        np.fill_diagonal(self.weights, 0)

    def recall(self, input_pattern, steps=5):
        pattern = input_pattern.copy()
        print(f"\nRecalling pattern: {pattern}")
        for _ in range(steps):
            for i in range(self.num_neurons):
                raw_input = np.dot(self.weights[i], pattern)
                pattern[i] = 1 if raw_input >= 0 else -1
            energy = self.energy(pattern)
            print(f"Pattern: {pattern}, Energy: {energy}")
        print(f"Final recalled pattern: {pattern}")
        return pattern

    def energy(self, pattern):
        return -0.5 * np.dot(pattern.T, np.dot(self.weights, pattern))


# Define 4 binary patterns (using bipolar representation: 1 and -1)
patterns = np.array([
    [1, -1, 1, -1],
    [-1, 1, -1, 1],
    [1, 1, -1, -1],
    [-1, -1, 1, 1]
])

# Create Hopfield network
hopfield_net = HopfieldNetwork(num_neurons=4)

# Train the network with 4 patterns
hopfield_net.train(patterns)
print("Weight matrix after training:")
print(hopfield_net.weights)

# Test the network with a known and a noisy version
test_patterns = [
    [1, -1, 1, -1],    # Known pattern
    [1, 1, 1, -1],     # Noisy version of pattern 1
    [-1, 1, 1, 1]      # Noisy version of pattern 2
]

# Recall stored patterns
for test in test_patterns:
    hopfield_net.recall(np.array(test))

Weight matrix after training:
[[ 0.  0.  0. -4.]
 [ 0.  0. -4.  0.]
 [ 0. -4.  0.  0.]
 [-4.  0.  0.  0.]]

Recalling pattern: [ 1 -1  1 -1]
Pattern: [ 1 -1  1 -1], Energy: -8.0
Pattern: [ 1 -1  1 -1], Energy: -8.0
Pattern: [ 1 -1  1 -1], Energy: -8.0
Pattern: [ 1 -1  1 -1], Energy: -8.0
Pattern: [ 1 -1  1 -1], Energy: -8.0
Final recalled pattern: [ 1 -1  1 -1]

Recalling pattern: [ 1  1  1 -1]
Pattern: [ 1 -1  1 -1], Energy: -8.0
Pattern: [ 1 -1  1 -1], Energy: -8.0
Pattern: [ 1 -1  1 -1], Energy: -8.0
Pattern: [ 1 -1  1 -1], Energy: -8.0
Pattern: [ 1 -1  1 -1], Energy: -8.0
Final recalled pattern: [ 1 -1  1 -1]

Recalling pattern: [-1  1  1  1]
Pattern: [-1 -1  1  1], Energy: -8.0
Pattern: [-1 -1  1  1], Energy: -8.0
Pattern: [-1 -1  1  1], Energy: -8.0
Pattern: [-1 -1  1  1], Energy: -8.0
Pattern: [-1 -1  1  1], Energy: -8.0
Final recalled pattern: [-1 -1  1  1]
